// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnX2uOOiJEswzPb3wyjFySAcSoqPuC6w4',
    appId: '1:1090710805189:web:99474db6a56aa0d282aeac',
    messagingSenderId: '1090710805189',
    projectId: 'grenciamentofila',
    authDomain: 'grenciamentofila.firebaseapp.com',
    storageBucket: 'grenciamentofila.firebasestorage.app',
    measurementId: 'G-7RNN1HG8FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFwY631RGq-_XNbMOvAIihnlKiMERcOps',
    appId: '1:1090710805189:android:482b2b361912369082aeac',
    messagingSenderId: '1090710805189',
    projectId: 'grenciamentofila',
    storageBucket: 'grenciamentofila.firebasestorage.app',
  );

}